version: '3'

services:
  app:
    build: .
    image: docker.cinna.dev/shutle
  production:
    imgae: docker.cinna.dev/shutle:${BUILD_NUMBER}
    command: python app.py
    volumes:
      - .:/code
    ports:
      - "80:80"